export const Constans = {
   DOG_BREEDS: [
    { value: "Desconocida", label: "Desconocida" },
    { value: "Mestizo", label: "Mestizo" },
    { value: "Akita Inu", label: "Akita Inu" },
    { value: "Boston Terrier", label: "Boston Terrier" },
    { value: "Border Collie", label: "Border Collie" },
    { value: "Boxer", label: "Boxer" },
    { value: "Bulldog Francés", label: "Bulldog Francés" },
    { value: "Bulldog Inglés", label: "Bulldog Inglés" },
    { value: "Bull Terrier", label: "Bull Terrier" },
    { value: "Chihuahua", label: "Chihuahua" },
    { value: "Chow Chow", label: "Chow Chow" },
    { value: "Cocker Spaniel", label: "Cocker Spaniel" },
    { value: "Dálmata", label: "Dálmata" },
    { value: "Dachshund", label: "Dachshund" },
    { value: "Doberman", label: "Doberman" },
    { value: "Golden Retriever", label: "Golden Retriever" },
    { value: "Husky Siberiano", label: "Husky Siberiano" },
    { value: "Labrador Retriever", label: "Labrador Retriever" },
    { value: "Maltés", label: "Maltés" },
    { value: "Poodle", label: "Poodle" },
    { value: "Rottweiler", label: "Rottweiler" },
    { value: "San Bernardo", label: "San Bernardo" },
    { value: "Shar Pei", label: "Shar Pei" },
    { value: "Shih Tzu", label: "Shih Tzu" },
    { value: "Yorkshire Terrier", label: "Yorkshire Terrier" },
  ],
  CAT_BREEDS: [
    { value: "Desconocida", label: "Desconocida" },
    { value: "Mestizo", label: "Mestizo" },
    { value: "Abisinio", label: "Abisinio" },
    { value: "American Curl", label: "American Curl" },
    { value: "Angora Turco", label: "Angora Turco" },
    { value: "Balinés", label: "Balinés" },
    { value: "Bengala", label: "Bengala" },
    { value: "Birmano", label: "Birmano" },
    { value: "Bosque de Noruega", label: "Bosque de Noruega" },
    { value: "Británico de Pelo Corto", label: "Británico de Pelo Corto" },
    { value: "Chartreux", label: "Chartreux" },
    { value: "Devon Rex", label: "Devon Rex" },
    { value: "Esfinge", label: "Esfinge" },
    { value: "Himalayo", label: "Himalayo" },
    { value: "Korato", label: "Korato" },
    { value: "Maine Coon", label: "Maine Coon" },
    { value: "Manx", label: "Manx" },
    { value: "Munchkin", label: "Munchkin" },
    { value: "Azul Ruso", label: "Azul Ruso" },
    { value: "Savannah", label: "Savannah" },
    { value: "Siamés", label: "Siamés" },
    { value: "Scottish Fold", label: "Scottish Fold" },
    { value: "Van Turco", label: "Van Turco" },
    { value: "Bombay", label: "Bombay" },
    { value: "Oriental de Pelo Corto", label: "Oriental de Pelo Corto" },
    { value: "Persa", label: "Persa" },
    { value: "Ragdoll", label: "Ragdoll" },
  ],
  PROVINCIAS_ESPAÑA: [
    { value: "Álava", label: "Álava" },
    { value: "Albacete", label: "Albacete" },
    { value: "Alicante", label: "Alicante" },
    { value: "Almería", label: "Almería" },
    { value: "Asturias", label: "Asturias" },
    { value: "Ávila", label: "Ávila" },
    { value: "Badajoz", label: "Badajoz" },
    { value: "Barcelona", label: "Barcelona" },
    { value: "Burgos", label: "Burgos" },
    { value: "Cáceres", label: "Cáceres" },
    { value: "Cádiz", label: "Cádiz" },
    { value: "Cantabria", label: "Cantabria" },
    { value: "Castellón", label: "Castellón" },
    { value: "Ciudad Real", label: "Ciudad Real" },
    { value: "Córdoba", label: "Córdoba" },
    { value: "Cuenca", label: "Cuenca" },
    { value: "Gerona", label: "Gerona" },
    { value: "Granada", label: "Granada" },
    { value: "Guadalajara", label: "Guadalajara" },
    { value: "Guipúzcoa", label: "Guipúzcoa" },
    { value: "Huelva", label: "Huelva" },
    { value: "Huesca", label: "Huesca" },
    { value: "Islas Baleares", label: "Islas Baleares" },
    { value: "Jaén", label: "Jaén" },
    { value: "La Coruña", label: "La Coruña" },
    { value: "La Rioja", label: "La Rioja" },
    { value: "Las Palmas", label: "Las Palmas" },
    { value: "León", label: "León" },
    { value: "Lérida", label: "Lérida" },
    { value: "Lugo", label: "Lugo" },
    { value: "Madrid", label: "Madrid" },
    { value: "Málaga", label: "Málaga" },
    { value: "Murcia", label: "Murcia" },
    { value: "Navarra", label: "Navarra" },
    { value: "Orense", label: "Orense" },
    { value: "Palencia", label: "Palencia" },
    { value: "Pontevedra", label: "Pontevedra" },
    { value: "Salamanca", label: "Salamanca" },
    { value: "Santa Cruz de Tenerife", label: "Santa Cruz de Tenerife" },
    { value: "Segovia", label: "Segovia" },
    { value: "Sevilla", label: "Sevilla" },
    { value: "Soria", label: "Soria" },
    { value: "Tarragona", label: "Tarragona" },
    { value: "Teruel", label: "Teruel" },
    { value: "Toledo", label: "Toledo" },
    { value: "Valencia", label: "Valencia" },
    { value: "Valladolid", label: "Valladolid" },
    { value: "Vizcaya", label: "Vizcaya" },
    { value: "Zamora", label: "Zamora" },
    { value: "Zaragoza", label: "Zaragoza" },
  ],
  MOTIVO_ABANDONO: [
    { value: "Encontrado en la calle", label: "Encontrado en la calle" },
    { value: "Problemas de comportamiento", label: "Problemas de comportamiento" },
    { value: "Alergias", label: "Alergias" },
    { value: "Nacimiento de hijo", label: "Nacimiento de hijo" },
    { value: "Traslado", label: "Traslado" },
    { value: "Pérdida de interés", label: "Pérdida de interés" },
    { value: "Camada", label: "Camada" },
    { value: "Falta de tiempo", label: "Falta de tiempo" },
    { value: "Fin temporada de caza", label: "Fin temporada de caza" },
    { value: "Defunción dueño", label: "Defunción dueño" },
    { value: "Vacaciones", label: "Vacaciones" },
    { value: "Otros", label: "Otros" },
  ],
  ESPECIE: [
    { value: "Perro", label: "Perro" },
    { value: "Gato", label: "Gato" },
    { value: "Conejo", label: "Conejo" },
    { value: "Hámster", label: "Hámster" },
    { value: "Cobaya", label: "Cobaya" },
    { value: "Ave (general)", label: "Ave (general)" },
    { value: "Pájaro", label: "Pájaro" },
    { value: "Pez", label: "Pez" },
    { value: "Tortuga", label: "Tortuga" },
    { value: "Hurón", label: "Hurón" },
    { value: "Erizo", label: "Erizo" },
    { value: "Rata", label: "Rata" },
    { value: "Ratón", label: "Ratón" },
    { value: "Chinchilla", label: "Chinchilla" },
    { value: "Reptil (general)", label: "Reptil (general)" },
    { value: "Otros", label: "Otros" },
  ],

  AGE: [
    { value: 'Cachorro', label: 'Cachorro' },
    { value: 'Joven', label: 'Joven' },
    { value: 'Adulto', label: 'Adulto' },
    { value: 'Anciano', label: 'Anciano' },
  ],

  VIVIENDA: [
    { value: 'Adosado', label: 'Adosado' },
    { value: 'Piso', label: 'Piso' },
    { value: 'Finca', label: 'Finca' },
  ],

  TIME: [
    { value: 'menos de 2h', label: 'menos de 2h' },
    { value: 'entre 2h y 4h', label: 'entre 2h y 4h' },
    { value: 'entre 4h y 8h', label: 'entre 4h y 8h' },
    { value: 'más 8h', label: 'más 8h' },
  ],

  VIAJE: [
    { value: 'Dejo agua y comida hasta la vuelta', label: 'Dejo agua y comida hasta la vuelta' },
    { value: 'Dejo a cargo a una persona responsable', label: 'Dejo a cargo a una persona responsable' },
    { value: 'Dejo en guardería', label: 'Dejo en guardería' },
    { value: 'No sé', label: 'No sé' },
  ],
};
